import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Abdel",
      email: "admin@gmail.com",
      password: bcrypt.hashSync("123456", 8),
      isAdmin: true,
      isVerified: true,
    },
    {
      name: "Tawab",
      email: "tawab@gmail.com",
      password: bcrypt.hashSync("123456", 8),
      isAdmin: false,
    },
    {
        name: "Lumia",
        email: "lumia@gmail.com",
        password: bcrypt.hashSync("123456", 8),
        isAdmin: false,
        isSeller: true,
        isVerified: true,
    }
  ],
  products: [
    {
      name: "bluetooth headphone",
      category: "technology",
      image: "images/p1.jfif",
      price: 99.99,
      stock: 100,
      brand: "Bluetooth",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "nike baskets",
      category: "sports",
      image: "images/p2.jfif",
      price: 199.99,
      stock: 0,
      brand: "Nike",
      rating: 4.0,
      numReviews: 7,
      description: "high quality product",
    },
    {
      name: "smart watch",
      category: "technology",
      image: "images/p3.jfif",
      price: 59.99,
      stock: 100,
      brand: "Apple",
      rating: 4.8,
      numReviews: 18,
      description: "high quality product",
    },
    {
      name: "sun glasses",
      category: "accessories",
      image: "images/p4.jfif",
      price: 29.99,
      stock: 100,
      brand: "Perlin",
      rating: 4.2,
      numReviews: 6,
      description: "high quality product",
    },
    {
      name: "chair",
      category: "house",
      image: "images/p5.jfif",
      price: 19.99,
      stock: 100,
      brand: "Brikoma",
      rating: 3.0,
      numReviews: 4,
      description: "medium quality product",
    },
    {
      name: "vintage camera",
      category: "technology",
      image: "images/p6.jfif",
      price: 99.99,
      stock: 100,
      brand: "Sony",
      rating: 4.9,
      numReviews: 59,
      description: "high quality product certified",
    },
  ],
};

export default data;
